name: Linux Build ipickme
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.org'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl libmagickwand-dev
      - name: Setup
        run: |
          mkdir -pv ~/Downloads
          mkdir -pv ~/quicklisp
          mkdir -pv ~/.cache/common-lisp
        shell: bash

      - name: Get Current Month
        id: current-month
        run: echo "::set-output name=value::$(date -u '+%Y-%m')"
      - name: Cache SBCL Setup
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: cache-sbcl-ubuntu-ipickme
        with:
          path: |
            ~/quicklisp
            ~/.cache/common-lisp
            ~/Downloads
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}"

      - name: Install quicklisp
        run: |
          cd ~/Downloads
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --non-interactive \
               --eval '(load "quicklisp.lisp")' \
               --eval '(quicklisp-quickstart:install)' \
               --eval '(ql-util:without-prompting (ql:add-to-init-file))' \
               --eval '(ql:update-all-dists)'
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Deps not on Quicklisp
        run: |
          cd ~/quicklisp/local-projects/
          test -d lisp-magick-wand || git clone --depth=1 https://github.com/ruricolist/lisp-magick-wand
          (cd lisp-magick-wand/    && git pull )

      - name: Symlink imagemagick
        run: |
          cd /usr/lib
          ls -l libMagickWand* || true
          cd x86_64-linux-gnu/
          ln -s libMagickWand-6.Q16.so libMagickWand.so

      - name: Build Binary
        run: |
          cd bin/
          make

      - uses: actions/upload-artifact@v2
        with:
          name: ipickme-linux-x86_64
          path: bin/ipickme
          if-no-files-found: error

      # - name: DEBUG SHELL
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ failure() }}
